index:
    path: /
    controller: App\Controller\SecurityController::indexPage

app_registration:
    path: /register
    controller: App\Controller\RegistrationController::userNew

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

app_profile:
    path: /profile/{userId}
    controller: App\Controller\ProfileController::showProfile
    requirements:
        userId: '\d+'
    defaults:
        userId: null

app_write_post:
    path: write_post
    controller: App\Controller\ProfileController::writePost

app_delete_post:
    path: /delete_post/{postId}
    controller: App\Controller\ProfileController::deletePost
    requirements:
        postId: '\d+'
    defaults:
        postId: null

app_settings:
    path: /settings
    controller: App\Controller\SettingsController::settingsPage

app_friends:
    path: /friends
    controller: App\Controller\FriendsController::viewFriends

app_explore:
    path: /explore
    controller: App\Controller\ExploreController::showExplore