index:
    path: /
    controller: App\Controller\SecurityController::login

app_registration:
    path: /register
    controller: App\Controller\RegistrationController::userNew

app_login:
    path: /login
    controller: App\Controller\SecurityController::login