index:
    path: /
    controller: App\Controller\SecurityController::indexPage

app_registration:
    path: /register
    controller: App\Controller\RegistrationController::userNew

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

app_profile:
    path: /profile
    controller: App\Controller\ProfileController::showProfile