index:
    path: /
    controller: App\Controller\SecurityController::indexPage

app_registration:
    path: /register
    controller: App\Controller\RegistrationController::userNew

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

app_profile:
    path: /profile
    controller: App\Controller\ProfileController::showProfile

app_delete_post:
    path: /delete_post/{post_id}
    controller: App\Controller\ProfileController::deletePost
    requirements:
        page: '\d+'
    defaults:
        post_id: null

app_settings:
    path: /settings
    controller: App\Controller\SettingsController::settingsPage

app_friends:
    path: /friends
    controller: App\Controller\FriendsController::viewFriends

app_explore:
    path: /explore
    controller: App\Controller\ExploreController::showExplore